<?php

namespace App\Filament\Resources\ProductResource\Pages\Concerns;

use App\Jobs\Seo\SyncJsonldSchema;
use App\Models\Category;
use App\Models\FilterGroup;
use Illuminate\Support\Str;

/**
 * Logic lưu translations + filter values dùng chung cho CreateProduct và EditProduct.
 */
trait ManagesProductRelations
{
    /**
     * Category IDs attached to the product BEFORE Filament synced the
     * `categories` relationship field — captured in EditProduct's
     * mutateFormDataBeforeSave() so syncCategoryJsonld() can also resync
     * categories the product was just REMOVED from (their numberOfItems
     * needs to go down too, not just up for newly-added ones).
     *
     * @var array<int, int|string>
     */
    protected array $categoryIdsBeforeSave = [];

    protected function captureCategoryIdsBeforeSave(): void
    {
        $this->categoryIdsBeforeSave = $this->getRecord()
            ->categories()
            ->pluck('categories.id')
            ->all();
    }

    protected function saveTranslations(): void
    {
        $record = $this->getRecord();
        $translationsData = $this->data['translations'] ?? [];

        foreach (config('app.supported_locales') as $locale) {
            $localeData = $translationsData[$locale] ?? [];

            if (empty($localeData['name'])) {
                continue;
            }

            $updateData = collect($localeData)
                ->only(['name', 'slug', 'short_description', 'description', 'info_sections', 'price', 'sale_price', 'currency'])
                ->map(fn ($v) => $v === '' ? null : $v)
                ->toArray();

            // Slug NOT NULL trên product_translations — derive từ name nếu bị bỏ trống
            if (empty($updateData['slug'])) {
                $updateData['slug'] = Str::slug($localeData['name']);
            }

            $record->translations()->updateOrCreate(['locale' => $locale], $updateData);
        }
    }

    protected function saveFilterValues(): void
    {
        $allSelectedIds = [];

        foreach (FilterGroup::active()->pluck('id') as $groupId) {
            $selected = $this->data["filter_group_{$groupId}"] ?? [];
            array_push($allSelectedIds, ...$selected);
        }

        $this->getRecord()->filterValues()->sync($allSelectedIds);
    }

    /**
     * Đẩy lại product lên Meilisearch sau khi translations + filter values đã lưu.
     * Scout chỉ tự re-index khi bảng products thay đổi — pivot sync() và
     * translation updateOrCreate() không trigger observer nào của Product.
     */
    protected function syncSearchIndex(): void
    {
        $this->getRecord()->searchable();
    }

    /**
     * Category JSON-LD (CollectionPage.numberOfItems + mainEntity ItemList)
     * is only regenerated by CategoryObserver when the Category model itself
     * saves — but Filament's `categories` relationship field sync()s the
     * pivot from the PRODUCT side, which fires no Category observer. Without
     * this, a category's product count/list JSON-LD silently goes stale the
     * moment a product is (re)assigned to it via the product form.
     *
     * Resyncs the union of before+after category IDs so both newly-added
     * and just-removed categories get their counts refreshed.
     */
    protected function syncCategoryJsonld(): void
    {
        $afterIds = $this->getRecord()->categories()->pluck('categories.id')->all();
        $categoryIds = array_unique([...$this->categoryIdsBeforeSave, ...$afterIds]);

        if (empty($categoryIds)) {
            return;
        }

        Category::whereIn('id', $categoryIds)->get()->each(function (Category $category): void {
            foreach (config('app.supported_locales') as $locale) {
                if ($category->translations()->where('locale', $locale)->exists()) {
                    dispatch(new SyncJsonldSchema($category, $locale))->onQueue('seo');
                }
            }
        });
    }
}
